In [1]:
import numpy as np

# サンプル数
num_samples = 10

# Gumbel(0, 1)分布からサンプリング
gumbel_samples = np.random.gumbel(loc=0, scale=1, size=num_samples)

# 結果の表示
print(gumbel_samples)


[-0.75732595  0.77317103 -0.03280656  0.97792386  0.90806082 -0.61106498
  0.83590159 -1.02373287  0.54207553 -1.05760535]


In [2]:
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

def compute_similarity(xi, hj, weight_vectors):
    # xiとhjを重みベクトルで重みづけ
    weighted_xi = [w * xi for w in weight_vectors]
    weighted_hj = [w * hj for w in weight_vectors]
    
    # 重みづけされたベクトル同士のコサイン類似度を計算
    similarities = [cosine_similarity([wx], [wh])[0, 0] for wx, wh in zip(weighted_xi, weighted_hj)]
    
    # 類似度の平均を計算
    average_similarity = np.mean(similarities)
    
    return average_similarity

# 例として、ランダムなベクトルや重みベクトルを用意
xi = np.random.rand(300)  # 300次元のランダムベクトル
hj = np.random.rand(300)  # 300次元のランダムベクトル
weight_vectors = [np.random.rand(300) for _ in range(5)]  # 5つの重みベクトル

# 類似度の計算
similarity = compute_similarity(xi, hj, weight_vectors)

# 結果の表示
print(f"Similarity: {similarity}")


Similarity: 0.7588801244480392


In [12]:
import numpy as np

def compute_similarity_matrix(X, H, weight_matrices):
    # XとHを各重みベクトルで要素ごとに重みづけ
    weighted_X = weight_matrices[:, None, :] * X[None, :, :]
    weighted_H = weight_matrices[:, None, :] * H[None, :, :]

    # 重みづけされたベクトル同士のコサイン類似度を計算
    numerator = np.sum(weighted_X[:, :, None, :] * weighted_H[:, None, :, :], axis=-1)
    denominator = np.linalg.norm(weighted_X, axis=-1)[:, :, None] * np.linalg.norm(weighted_H, axis=-1)[:, None, :]

    # 類似度の計算
    similarities = numerator / denominator

    return similarities

# 例として、ランダムな行列XとH、および5つのランダムな300次元の重みベクトルを用意
X = np.random.rand(10, 300)  # 10行300列のランダム行列
H = np.random.rand(8, 300)   # 8行300列のランダム行列
weight_matrices = np.random.rand(5, 300)  # 5つのランダムな300次元の重みベクトル

# 類似度の計算
similarities = compute_similarity_matrix(X, H, weight_matrices)

# 結果の表示
print(f"Shape of Similarity Matrix S: {similarities.shape}")
# print(f"Similarity Matrix S:\n{similarities}")


Shape of Similarity Matrix S: (5, 10, 8)
Similarity Matrix S:
[[[0.72170549 0.74466962 0.75442993 0.72926793 0.75885162 0.75623697
   0.80247929 0.78059372]
  [0.73857753 0.74844628 0.72165759 0.72486635 0.76337127 0.76733505
   0.74073947 0.73448043]
  [0.70795111 0.75271518 0.73152537 0.75341771 0.75134152 0.77857834
   0.70983922 0.73691625]
  [0.76044966 0.77483683 0.72183097 0.75290315 0.77020697 0.78366312
   0.73705193 0.76074919]
  [0.74415637 0.71345751 0.74872243 0.73935775 0.77531874 0.78291042
   0.71653041 0.76597643]
  [0.77440768 0.77445729 0.76461356 0.7458649  0.77508956 0.786261
   0.74440628 0.74481199]
  [0.76818575 0.71881975 0.73955285 0.74026594 0.74948334 0.80143742
   0.76796341 0.72506399]
  [0.77468941 0.72203262 0.72865093 0.70897984 0.72401692 0.73613322
   0.73207191 0.76889932]
  [0.75283302 0.71608174 0.73182622 0.70053793 0.72593673 0.79652392
   0.74752991 0.74013667]
  [0.74863717 0.74721637 0.73385667 0.71802429 0.75398225 0.78287615
   0.74316728 0.

In [31]:
import numpy as np

def compute_similarity_matrix(X, H, weight_matrices):
    # XとHを各重みベクトルで要素ごとに重みづけ
    weighted_X = weight_matrices[:, None, :] * X[None, :, :]
    weighted_H = weight_matrices[:, None, :] * H[None, :, :]

    # 重みづけされたベクトル同士のコサイン類似度を計算
    numerator = np.sum(weighted_X[:, :, None, :] * weighted_H[:, None, :, :], axis=-1)
    denominator = np.linalg.norm(weighted_X, axis=-1)[:, :, None] * np.linalg.norm(weighted_H, axis=-1)[:, None, :]

    # 類似度の計算
    similarities = numerator / denominator

    # 最後に類似度の平均をとる
    average_similarity = np.mean(similarities, axis=(0))

    return average_similarity

# 例として、ランダムな行列XとH、および5つのランダムな300次元の重みベクトルを用意
X = np.random.rand(2000, 300)  # 10行300列のランダム行列
H = np.random.rand(2500, 300)   # 8行300列のランダム行列
weight_matrices = np.random.rand(5, 300)  # 5つのランダムな300次元の重みベクトル

# 類似度の計算
similarities = compute_similarity_matrix(X, H, weight_matrices)

# 結果の表示
print(f"Shape of Similarity Matrix S: {similarities.shape}")
# print(f"Similarity Matrix S:\n{similarities}")


Shape of Similarity Matrix S: (2000, 2500)


In [37]:
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

def compute_similarity_matrix(X, H, weight_matrices):
    # XとHを各重みベクトルで要素ごとに重みづけ
    # weighted_X = weight_matrices[:, None, :] * X[None, :, :]
    # weighted_H = weight_matrices[:, None, :] * H[None, :, :]

    # ベクトル同士のコサイン類似度を計算
    similarities = cosine_similarity(X, H)

    # 形状を元に戻す
    # similarities = similarities.reshape((weight_matrices.shape[0], X.shape[0], H.shape[0]))

    # 最後に類似度の平均をとる
    # average_similarity = np.mean(similarities, axis=(0))

    return similarities

# 例として、ランダムな行列XとH、および5つのランダムな50次元の重みベクトルを用意
X = np.random.rand(2000, 50)  # 2000行50列のランダム行列
H = np.random.rand(2500, 50)   # 2500行50列のランダム行列
weight_matrices = np.random.rand(5, 50)  # 5つのランダムな50次元の重みベクトル

# 類似度の計算
similarities = compute_similarity_matrix(X, H, weight_matrices)

# 結果の表示
print(f"Shape of Similarity Matrix S: {similarities.shape}")


Shape of Similarity Matrix S: (2000, 2500)


In [38]:
import numpy as np

def sparsify_residual_hypergraph(S, padd):
    # Sij ∈ top(S, padd) なるインデックスを取得
    top_indices = np.argsort(S, axis=None)[-int(padd * S.size):]
    top_indices = np.unravel_index(top_indices, S.shape)

    # ∆H を初期化し、条件に基づいて更新
    delta_H = np.zeros_like(S)
    delta_H[top_indices] = 1

    return delta_H

# 例として、ランダムな類似度行列Sとpaddの設定
S = similarities  # 10行8列のランダムな類似度行列
padd = 0.2  # paddの設定（例として0.2）

# ∆Hの計算
delta_H = sparsify_residual_hypergraph(S, padd)

# 結果の表示
print("Original Similarity Matrix S:\n", S)
print(f"\nThreshold Padd: {padd}")
print("\nSparse Residual Hypergraph Structure ∆H:\n", delta_H)


Original Similarity Matrix S:
 [[0.76476584 0.79407114 0.7332108  ... 0.74834192 0.76767119 0.71058369]
 [0.81380124 0.72782257 0.74553753 ... 0.66817478 0.76552082 0.75656667]
 [0.70943869 0.73726766 0.73730553 ... 0.70611923 0.75846901 0.74852535]
 ...
 [0.64859318 0.68419978 0.68054361 ... 0.67688171 0.74624207 0.72642998]
 [0.7266724  0.72969489 0.66719796 ... 0.74771545 0.81942909 0.81118321]
 [0.69930834 0.66311968 0.69231891 ... 0.71608449 0.80742114 0.78125681]]

Threshold Padd: 0.2

Sparse Residual Hypergraph Structure ∆H:
 [[0. 1. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 1.]
 [0. 0. 0. ... 0. 1. 0.]]


In [22]:
import numpy as np

def sparsify_residual_hypergraph(S, padd, original_connections):
    # Sij ∈ top(S, padd) なるインデックスを取得
    top_indices = np.argsort(S, axis=None)[-int(padd * S.size):]
    top_indices = np.unravel_index(top_indices, S.shape)

    # ∆H を初期化し、条件に基づいて更新
    delta_H = np.zeros_like(S)
    delta_H[top_indices] = 1

    # Hij = 0 かつ Sij ∈ top(S, padd) の場合、∆Hij = 1 とする
    delta_H = np.where((original_connections == 0) & (delta_H == 1), 1, 0)

    return delta_H

# 例として、ランダムな類似度行列Sとランダムな0または1の要素を持つ10×8のHijを生成
S = np.random.rand(10, 8)  # 10行8列のランダムな類似度行列
original_connections = np.random.randint(2, size=(10, 8))  # 0または1のランダムな10×8の行列
padd = 0.2  # paddの設定（例として0.2）

# ∆Hの計算
delta_H = sparsify_residual_hypergraph(S, padd, original_connections)

# 結果の表示
print("Original Similarity Matrix S:\n", S)
print("\nOriginal Hypergraph Structure H:\n", original_connections)
print(f"\nThreshold Padd: {padd}")
print("\nSparse Residual Hypergraph Structure ∆H:\n", delta_H)


Original Similarity Matrix S:
 [[0.2421557  0.20255876 0.65636414 0.6671348  0.60567918 0.1765118
  0.3147378  0.16139861]
 [0.17441088 0.89969018 0.16910072 0.68212474 0.92522437 0.68532618
  0.99748686 0.96217281]
 [0.94575924 0.70822651 0.11457328 0.61319642 0.85544617 0.29846297
  0.37044649 0.67759247]
 [0.99479312 0.89649799 0.39318324 0.79119313 0.4622452  0.88426665
  0.5111331  0.8580635 ]
 [0.91654219 0.23857365 0.65611565 0.5059415  0.00264665 0.46880323
  0.78470667 0.34716833]
 [0.80985455 0.4661992  0.00484452 0.12463024 0.3704152  0.90950536
  0.5296558  0.23818284]
 [0.11726684 0.55926656 0.04204345 0.98386363 0.497373   0.9865708
  0.74685577 0.40121339]
 [0.25898339 0.68524307 0.49095259 0.29452661 0.46433413 0.17256475
  0.62244914 0.12207616]
 [0.62165386 0.42693681 0.67921164 0.28604127 0.6689141  0.43442613
  0.46079725 0.01667868]
 [0.19865221 0.64475424 0.05372382 0.58164901 0.61102353 0.93958653
  0.22329474 0.55417785]]

Original Hypergraph Structure H:
 [[1 0

In [24]:
import numpy as np

def gumbel_softmax(logits, temperature=1.0):
    gumbel_noise = -np.log(-np.log(np.random.rand(*logits.shape)))
    softmax_output = np.exp((logits + gumbel_noise) / temperature) / np.exp((logits + gumbel_noise) / temperature).sum(axis=-1, keepdims=True)
    return softmax_output

def calculate_Zvij(xi, hj, mlp_weights):
    mlp_input = np.concatenate([xi, hj], axis=-1)
    mlp_output = np.dot(mlp_input, mlp_weights)
    Zvij = gumbel_softmax(mlp_output)
    return Zvij

def calculate_Mvij(Zvij, temperature=1.0):
    epsilon_0 = np.random.gumbel(0, 1, size=Zvij.shape)
    epsilon_1 = np.random.gumbel(0, 1, size=Zvij.shape)
    Mvij = 1 / (1 + np.exp((np.log(Zvij) - np.log(1 - Zvij) + epsilon_0 - epsilon_1) / temperature))
    return Mvij

# 例として、ランダムなベクトルxiとhj、およびMLPの重み行列を生成
xi = np.random.rand(300)  # 300次元のランダムベクトル
hj = np.random.rand(300)  # 300次元のランダムベクトル
mlp_weights = np.random.rand(600, 1)  # 600次元のMLPの重み行列

# 温度パラメータを設定
temperature = 0.2

# Zvijの計算
Zvij = calculate_Zvij(xi, hj, mlp_weights)

# Mvijの計算
Mvij = calculate_Mvij(Zvij, temperature)

# 結果の表示
print(f"Zvij:\n{Zvij}")
print(f"Mvij:\n{Mvij}")


Zvij:
[1.]
Mvij:
[0.]


/tmp/ipykernel_4008/1695196027.py:17: RuntimeWarning: divide by zero encountered in log
  Mvij = 1 / (1 + np.exp((np.log(Zvij) - np.log(1 - Zvij) + epsilon_0 - epsilon_1) / temperature))


In [26]:
def calculate_H(H, Mvij, delta_H, E, N):
    I = np.zeros_like(H)
    E_indices, N_indices = np.arange(E), np.arange(N)
    I[E_indices[:, None] + N, N_indices] = 1

    H_new = Mvij * (H + delta_H) + I
    return H_new

# 例として、ランダムな行列Hとdelta_H、およびMvijの生成
H = np.random.rand(10, 8)  # 10行8列のランダム行列
delta_H = np.random.rand(10, 8)  # 10行8列のランダム行列
Mvij = np.random.rand(10, 8)  # 10行8列のランダム行列

# EとNの設定
E, N = 2, 3

# Hの更新
H_new = calculate_H(H, Mvij, delta_H, E, N)

# 結果の表示
print(f"H_new:\n{H_new}")


H_new:
[[0.96445748 1.30585797 0.28657013 0.24923662 0.02591257 0.71320091
  1.28757729 0.33768663]
 [0.42369893 0.12740756 0.52117965 0.78376985 0.60402181 0.55914571
  0.62499286 0.59065779]
 [0.09207111 0.33495748 0.56581788 0.21769254 0.78619303 0.10581853
  0.10708234 0.37364129]
 [1.67036608 1.26062884 1.75906878 0.28679184 0.45771533 0.51584465
  0.21838073 0.53661267]
 [1.51567815 1.23864762 1.22415186 0.00278174 0.21432357 0.67107776
  0.05513312 0.14404983]
 [0.63870756 0.83103434 0.65956204 0.73923454 0.86439712 0.21339498
  1.29116929 0.8161523 ]
 [0.14283508 0.20834146 0.82687531 0.16683651 0.19224239 0.85408526
  0.10322303 0.22927661]
 [1.07293443 0.76347887 0.65527581 0.54470772 0.64435455 0.42497833
  1.35028573 0.92752549]
 [0.9084389  0.08474892 0.4110021  0.37247067 0.773224   1.16584815
  0.82015976 1.0333787 ]
 [0.47398926 0.82100538 0.53047788 0.08738916 0.4942123  0.3897364
  0.12575733 0.12113216]]


In [29]:
def calculate_H(H, Mvij, delta_H, E, N):
    I = np.zeros_like(H)
    for i in range(E):
        for j in range(N):
            I[i, j] = 1

    H_new = Mvij * (H + delta_H) + I
    return H_new

# 例として、ランダムな行列Hとdelta_H、およびMvijの生成
H = np.random.rand(10, 8)  # 10行8列のランダム行列
delta_H = np.random.rand(10, 8)  # 10行8列のランダム行列
Mvij = np.random.rand(10, 8)  # 10行8列のランダム行列

# EとNの設定
E, N = 10, 8

# Hの更新
H_new = calculate_H(H, Mvij, delta_H, E, N)

# 結果の表示
print(f"H_new:\n{H_new}")


H_new:
[[1.56492902 1.85431791 1.07616423 1.95805188 1.86272267 1.09377319
  2.22468643 1.05130149]
 [1.01156971 1.52810572 1.21187493 1.69515704 1.31195575 1.17757233
  2.01788712 1.09616008]
 [2.00577002 1.02739378 2.03905871 2.02660339 1.21063368 1.67712188
  1.346081   1.98594817]
 [2.04810269 1.64077177 1.25431905 1.56990265 1.22057609 1.89136443
  2.25970183 1.38667153]
 [1.21107334 1.86300574 1.56806958 1.31636537 1.99120691 1.20289878
  1.84513632 1.11571523]
 [2.21274747 1.5592926  2.05096561 1.45537709 1.38859047 2.03562157
  1.54588927 1.50098461]
 [1.08543563 1.46811884 1.12247394 1.08265358 1.78358113 1.23636892
  2.87208491 1.44544649]
 [1.54719545 1.73863236 1.62706027 2.25565749 1.07340746 1.20831759
  1.64514037 2.2482767 ]
 [1.03404841 2.04345167 2.00913307 1.32309871 2.36003909 1.56170271
  1.32482801 2.26259344]
 [1.38030138 1.74823099 1.80705933 1.05357653 1.08369177 1.39470101
  1.35839157 1.26414162]]


In [30]:
import numpy as np

def calculate_H(H, Mvij, delta_H, E, N):
    I = np.zeros_like(H)
    for i in range(E):
        for j in range(N):
            I[i, j] = 1

    H_new = Mvij * (H + delta_H) + I
    return H_new

# 例として、ランダムな行列Hとdelta_H、およびMvijの生成
H = np.random.rand(10, 8)  # 10行8列のランダム行列
delta_H = np.random.rand(10, 8)  # 10行8列のランダム行列
Mvij = np.random.rand(10, 8)  # 10行8列のランダム行列

# EとNの設定
E, N = 10, 8

# Hの更新
H_new = calculate_H(H, Mvij, delta_H, E, N)

# 結果とサイズの表示
print(f"H_new:\n{H_new}")
print(f"Shape of H_new: {H_new.shape}")


H_new:
[[2.7463719  2.20239422 1.01098245 1.82606944 1.47774737 2.13861596
  1.39679147 1.25488556]
 [1.22350403 1.42879374 2.26016834 1.91738141 1.30556311 1.41453999
  1.27779713 1.20984263]
 [1.68311041 1.33422429 1.61771529 1.02500259 1.28896227 1.07494704
  1.49164208 1.68191914]
 [1.16030403 1.44647525 1.00349612 2.22058119 1.4160494  1.40908851
  2.28138698 1.24235118]
 [1.83205772 1.11461808 1.27673644 1.66434728 1.27484331 1.58472204
  1.63604206 1.04271904]
 [1.45840548 1.68806704 2.24843978 1.35336909 2.18404445 1.64800245
  1.29807795 1.78949428]
 [1.89504402 2.01810762 1.20502243 1.53251522 1.36589333 1.26688802
  1.41588017 1.12813974]
 [1.21379372 1.12405439 1.2432784  1.8927342  1.00663197 1.5082828
  1.36673756 1.36690904]
 [1.34193673 1.68653323 1.07813592 1.41288252 1.22938995 2.20699863
  2.04181185 1.8570783 ]
 [1.44665177 1.35871689 1.69628392 1.02017949 1.12801185 2.50172909
  1.25430014 1.28969888]]
Shape of H_new: (10, 8)


In [39]:
import numpy as np

def gumbel_softmax_batch(logits, temperature=1.0):
    gumbel_noise = -np.log(-np.log(np.random.rand(*logits.shape)))
    softmax_output = np.exp((logits + gumbel_noise) / temperature) / np.exp((logits + gumbel_noise) / temperature).sum(axis=-1, keepdims=True)
    return softmax_output

def calculate_Zvij_batch(X, H, mlp_weights):
    mlp_input = np.concatenate([X[:, None, :], H[:, :, None, :]], axis=-1)
    mlp_output = np.dot(mlp_input, mlp_weights)
    Zvij = gumbel_softmax_batch(mlp_output)
    return Zvij

def calculate_Mvij_batch(Zvij, temperature=1.0):
    epsilon_0 = np.random.gumbel(0, 1, size=Zvij.shape)
    epsilon_1 = np.random.gumbel(0, 1, size=Zvij.shape)
    Mvij = 1 / (1 + np.exp((np.log(Zvij) - np.log(1 - Zvij) + epsilon_0 - epsilon_1) / temperature))
    return Mvij

# 例として、ランダムな行列XとH、およびMLPの重み行列を生成
X = np.random.rand(100, 300)  # 100行300列のランダム行列
H = np.random.rand(80, 300)   # 80行300列のランダム行列
mlp_weights = np.random.rand(600, 1)  # 600次元のMLPの重み行列

# 温度パラメータを設定
temperature = 0.2

# Zvijの計算
Zvij = calculate_Zvij_batch(X, H, mlp_weights)

# Mvijの計算
Mvij = calculate_Mvij_batch(Zvij, temperature)

# 結果の表示
print(f"Shape of Zvij: {Zvij.shape}")
print(f"Shape of Mvij: {Mvij.shape}")


IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed

In [40]:
import numpy as np

def gumbel_softmax_batch(logits, temperature=1.0):
    gumbel_noise = -np.log(-np.log(np.random.rand(*logits.shape)))
    softmax_output = np.exp((logits + gumbel_noise) / temperature) / np.exp((logits + gumbel_noise) / temperature).sum(axis=-1, keepdims=True)
    return softmax_output

def calculate_Zvij_batch(X, H, mlp_weights):
    mlp_input = np.concatenate([X[:, None, :], H[None, :, :]], axis=-1)
    mlp_output = np.dot(mlp_input, mlp_weights)
    Zvij = gumbel_softmax_batch(mlp_output)
    return Zvij

def calculate_Mvij_batch(Zvij, temperature=1.0):
    epsilon_0 = np.random.gumbel(0, 1, size=Zvij.shape)
    epsilon_1 = np.random.gumbel(0, 1, size=Zvij.shape)
    Mvij = 1 / (1 + np.exp((np.log(Zvij) - np.log(1 - Zvij) + epsilon_0 - epsilon_1) / temperature))
    return Mvij

# 例として、ランダムな行列XとH、およびMLPの重み行列を生成
X = np.random.rand(100, 300)  # 100行300列のランダム行列
H = np.random.rand(80, 300)   # 80行300列のランダム行列
mlp_weights = np.random.rand(600, 1)  # 600次元のMLPの重み行列

# 温度パラメータを設定
temperature = 0.2

# Zvijの計算
Zvij = calculate_Zvij_batch(X, H, mlp_weights)

# Mvijの計算
Mvij = calculate_Mvij_batch(Zvij, temperature)

# 結果の表示
print(f"Shape of Zvij: {Zvij.shape}")
print(f"Shape of Mvij: {Mvij.shape}")


ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 100 and the array at index 1 has size 1

In [43]:
import numpy as np

def gumbel_softmax(logits, temperature=1.0):
    gumbel_noise = -np.log(-np.log(np.random.rand(*logits.shape)))
    softmax_output = np.exp((logits + gumbel_noise) / temperature) / np.exp((logits + gumbel_noise) / temperature).sum(axis=-1, keepdims=True)
    return softmax_output

def calculate_Zv_and_Mv(X, H, mlp_weights, temperature=1.0):
    # 行列 X と H を結合
    concatenated_input = np.concatenate([X[:, None, :], H[None, :, :]], axis=-1)

    # MLP で Zv を計算
    mlp_output = np.dot(concatenated_input, mlp_weights)
    Zv = gumbel_softmax(mlp_output, temperature)

    # Gumbel Softmax で Mv を計算
    epsilon_0 = np.random.gumbel(0, 1, size=Zv.shape)
    epsilon_1 = np.random.gumbel(0, 1, size=Zv.shape)
    Mv = 1 / (1 + np.exp((np.log(Zv) - np.log(1 - Zv) + epsilon_0 - epsilon_1) / temperature))

    return Zv, Mv

# 例として、ランダムな行列 X と H、および MLP の重み行列を生成
X = np.random.rand(100, 300)  # 100行300列のランダム行列
H = np.random.rand(80, 300)   # 80行300列のランダム行列
mlp_weights = np.random.rand(600, 1)  # 600次元のMLPの重み行列

# 温度パラメータを設定
temperature = 0.2

# Zv と Mv の計算
Zv, Mv = calculate_Zv_and_Mv(X, H, mlp_weights, temperature)

# 結果の表示
print(f"Zv shape: {Zv.shape}")
print(f"Mv shape: {Mv.shape}")


ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 100 and the array at index 1 has size 1

Augmnentation test

In [56]:
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
from torchmetrics.functional import pairwise_cosine_similarity

def compute_similarity_matrix(X, H, weight_matrices):
    # XとHを各重みベクトルで要素ごとに重みづけ
    # weighted_X = weight_matrices[:, None, :] * X[None, :, :]
    # weighted_H = weight_matrices[:, None, :] * H[None, :, :]

    # ベクトル同士のコサイン類似度を計算
    similarities = cosine_similarity(X, H)

    # 形状を元に戻す
    # similarities = similarities.reshape((weight_matrices.shape[0], X.shape[0], H.shape[0]))

    # 最後に類似度の平均をとる
    # average_similarity = np.mean(similarities, axis=(0))

    return similarities

# 例として、ランダムな行列XとH、および5つのランダムな50次元の重みベクトルを用意
X = np.random.rand(2000, 50)  # 2000行50列のランダム行列
H = np.random.rand(2500, 50)   # 2500行50列のランダム行列
weight_matrices = np.random.rand(5, 50)  # 5つのランダムな50次元の重みベクトル

# 類似度の計算
similarities = compute_similarity_matrix(X, H, weight_matrices)

# 結果の表示
print(f"Shape of Similarity Matrix S: {similarities.shape}")


Shape of Similarity Matrix S: (2000, 2500)


In [55]:
import torch
import numpy as np
from torchmetrics.functional import pairwise_cosine_similarity

def compute_similarity_matrix(X, H, weight_matrices):
    # NumPy配列をPyTorchのテンソルに変換
    X_tensor = torch.tensor(X, dtype=torch.float32)
    H_tensor = torch.tensor(H, dtype=torch.float32)

    # ベクトル同士のコサイン類似度を計算
    similarities = pairwise_cosine_similarity(X_tensor, H_tensor)

    # 形状を元に戻す
    # similarities = similarities.reshape((weight_matrices.shape[0], X.shape[0], H.shape[0]))

    # 最後に類似度の平均をとる
    # average_similarity = torch.mean(similarities, dim=0)

    return similarities.numpy()

# 例として、ランダムな行列XとH、および5つのランダムな50次元の重みベクトルを用意
X = np.random.rand(2000, 50)
H = np.random.rand(2500, 50)
weight_matrices = np.random.rand(5, 50)

# 類似度の計算
similarities = compute_similarity_matrix(X, H, weight_matrices)

# 結果の表示
print(f"Shape of Similarity Matrix S: {similarities.shape}")


Shape of Similarity Matrix S: (2000, 2500)


In [45]:
import numpy as np

def sparsify_residual_hypergraph(S, padd):
    # Sij ∈ top(S, padd) なるインデックスを取得
    top_indices = np.argsort(S, axis=None)[-int(padd * S.size):]
    top_indices = np.unravel_index(top_indices, S.shape)

    # ∆H を初期化し、条件に基づいて更新
    delta_H = np.zeros_like(S)
    delta_H[top_indices] = 1

    return delta_H

# 例として、ランダムな類似度行列Sとpaddの設定
S = similarities  # 10行8列のランダムな類似度行列
padd = 0.2  # paddの設定（例として0.2）

# ∆Hの計算
delta_H = sparsify_residual_hypergraph(S, padd)

# 結果の表示
print("Original Similarity Matrix S:\n", S)
print(f"\nThreshold Padd: {padd}")
print("\nSparse Residual Hypergraph Structure ∆H:\n", delta_H)


Original Similarity Matrix S:
 [[0.79142661 0.71178958 0.76653226 ... 0.78592776 0.64937173 0.81739442]
 [0.79544696 0.73278497 0.71575509 ... 0.70464985 0.71698694 0.72681481]
 [0.76365017 0.77337271 0.80723859 ... 0.81292286 0.73311453 0.78494889]
 ...
 [0.76567529 0.75905927 0.84670424 ... 0.7839514  0.71618988 0.77462489]
 [0.79695826 0.74925907 0.76949224 ... 0.82465223 0.78466913 0.76559352]
 [0.79914746 0.76578298 0.79661495 ... 0.77113744 0.67891072 0.7949222 ]]

Threshold Padd: 0.2

Sparse Residual Hypergraph Structure ∆H:
 [[1. 0. 0. ... 0. 0. 1.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 1. 0. 0.]
 ...
 [0. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 1. 0. 0.]
 [1. 0. 1. ... 0. 0. 1.]]


In [47]:
import numpy as np

def sparsify_residual_hypergraph(S, padd):
    top_indices = np.argsort(S, axis=None)[-int(padd * S.size):]
    top_indices = np.unravel_index(top_indices, S.shape)
    delta_H = np.zeros_like(S)
    delta_H[top_indices] = 1
    return delta_H

def create_H_hat(original_H, delta_H):
    H_hat = original_H + delta_H
    return H_hat

# 例として、ランダムな類似度行列 S と padd の設定
S = similarities  # 10行8列のランダムな類似度行列
padd = 0.2  # paddの設定（例として0.2）

# ∆Hの計算
delta_H = sparsify_residual_hypergraph(S, padd)

# 例として、ランダムなバイナリ行列 original_H の生成
original_H = np.random.randint(2, size=(2000, 2500))

# H_hatの計算
H_hat = create_H_hat(original_H, delta_H)

# 結果の表示
print("Original Binary Matrix H:\n", original_H)
print("\nSparse Residual Hypergraph Structure ∆H:\n", delta_H)
print("\nUpdated Binary Matrix H_hat:\n", H_hat)


Original Binary Matrix H:
 [[0 1 0 ... 0 1 0]
 [1 0 0 ... 1 1 1]
 [1 0 1 ... 1 0 0]
 ...
 [1 0 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [0 0 0 ... 1 0 0]]

Sparse Residual Hypergraph Structure ∆H:
 [[1. 0. 0. ... 0. 0. 1.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 1. 0. 0.]
 ...
 [0. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 1. 0. 0.]
 [1. 0. 1. ... 0. 0. 1.]]

Updated Binary Matrix H_hat:
 [[1. 1. 0. ... 0. 1. 1.]
 [2. 0. 0. ... 1. 1. 1.]
 [1. 0. 2. ... 2. 0. 0.]
 ...
 [1. 0. 2. ... 1. 1. 1.]
 [2. 1. 1. ... 2. 1. 1.]
 [1. 0. 1. ... 1. 0. 1.]]


In [52]:

def nabla_residual_hypergraph(S, padd):
    bottom_indices = np.argsort(S, axis=None)[:int(padd * S.size)]
    bottom_indices = np.unravel_index(bottom_indices, S.shape)
    delta_H = np.zeros_like(S)
    delta_H[bottom_indices] = 1
    return delta_H
import numpy as np

def delta_residual_hypergraph(S, padd):
    top_indices = np.argsort(S, axis=None)[-int(padd * S.size):]
    top_indices = np.unravel_index(top_indices, S.shape)
    delta_H = np.zeros_like(S)
    delta_H[top_indices] = 1
    return delta_H

def create_H_hat(original_H, delta_H, nabla_H):
    H_hat = original_H + delta_H - nabla_H
    return H_hat

# 例として、ランダムな類似度行列 S と padd の設定
S = similarities  # 10行8列のランダムな類似度行列
padd = 0.2  # paddの設定（例として0.2）

# ∆Hの計算
delta_H = delta_residual_hypergraph(S, padd)
nabla_H = nabla_residual_hypergraph(S, padd)

# 例として、ランダムなバイナリ行列 original_H の生成
original_H = np.random.randint(2, size=(2000, 2500))

# H_hatの計算
H_hat = create_H_hat(original_H, delta_H, nabla_H)

# 結果の表示
print("Original Binary Matrix H:\n", original_H)
print("\nSparse Residual Hypergraph Structure ∆H:\n", delta_H)
print("\nSparse Residual Hypergraph Structure ∇H:\n", nabla_H)
print("\nUpdated Binary Matrix H_hat:\n", H_hat)


Original Binary Matrix H:
 [[1 0 1 ... 0 0 1]
 [1 1 1 ... 1 0 0]
 [1 0 0 ... 1 0 1]
 ...
 [0 1 1 ... 0 0 1]
 [0 0 0 ... 1 1 1]
 [1 1 1 ... 1 0 0]]

Sparse Residual Hypergraph Structure ∆H:
 [[1. 0. 0. ... 0. 0. 1.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 1. 0. 0.]
 ...
 [0. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 1. 0. 0.]
 [1. 0. 1. ... 0. 0. 1.]]

Sparse Residual Hypergraph Structure ∇H:
 [[0. 1. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]]

Updated Binary Matrix H_hat:
 [[ 2. -1.  1. ...  0. -1.  2.]
 [ 2.  1.  1. ...  0.  0.  0.]
 [ 1.  0.  1. ...  2.  0.  1.]
 ...
 [ 0.  1.  2. ...  0.  0.  1.]
 [ 1.  0.  0. ...  2.  1.  1.]
 [ 2.  1.  2. ...  1. -1.  1.]]


In [53]:
import numpy as np

def nabla_residual_hypergraph(S, padd):
    bottom_indices = np.argsort(S, axis=None)[:int(padd * S.size)]
    bottom_indices = np.unravel_index(bottom_indices, S.shape)
    nabla_H = np.zeros_like(S)
    nabla_H[bottom_indices] = 1
    return nabla_H

def delta_residual_hypergraph(S, padd):
    top_indices = np.argsort(S, axis=None)[-int(padd * S.size):]
    top_indices = np.unravel_index(top_indices, S.shape)
    delta_H = np.zeros_like(S)
    delta_H[top_indices] = 1
    return delta_H

def create_H_hat(original_H, delta_H, nabla_H):
    H_hat = np.clip(original_H + delta_H - nabla_H, 0, 1)  # 0以下の値を0に、1以上の値を1にクリップ
    return H_hat

# 例として、ランダムな類似度行列 S と padd の設定
S = similarities  # 10行8列のランダムな類似度行列
padd = 0.2  # paddの設定（例として0.2）

# ∆Hと∇Hの計算
delta_H = delta_residual_hypergraph(S, padd)
nabla_H = nabla_residual_hypergraph(S, padd)

# 例として、ランダムなバイナリ行列 original_H の生成
original_H = np.random.randint(2, size=(2000, 2500))

# H_hatの計算
H_hat = create_H_hat(original_H, delta_H, nabla_H)

# 結果の表示
print("Original Binary Matrix H:\n", original_H)
print("\nSparse Residual Hypergraph Structure ∆H:\n", delta_H)
print("\nSparse Residual Hypergraph Structure ∇H:\n", nabla_H)
print("\nUpdated Binary Matrix H_hat:\n", H_hat)


Original Binary Matrix H:
 [[1 1 1 ... 0 1 1]
 [1 0 1 ... 0 1 0]
 [1 1 1 ... 0 1 1]
 ...
 [1 1 1 ... 0 0 0]
 [0 0 0 ... 0 0 1]
 [1 1 1 ... 1 0 1]]

Sparse Residual Hypergraph Structure ∆H:
 [[1. 0. 0. ... 0. 0. 1.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 1. 0. 0.]
 ...
 [0. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 1. 0. 0.]
 [1. 0. 1. ... 0. 0. 1.]]

Sparse Residual Hypergraph Structure ∇H:
 [[0. 1. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]]

Updated Binary Matrix H_hat:
 [[1. 0. 1. ... 0. 0. 1.]
 [1. 0. 1. ... 0. 1. 0.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 1. 0. 1.]
 [1. 1. 1. ... 1. 0. 1.]]


In [58]:
import torch as t

class YourClassName:
    def LearnedHyperGraph(self, H, S):
        def nabla_residual_hypergraph(S, padd):
            values, indices = t.sort(S.view(-1))
            bottom_indices = indices[:int(padd * S.numel())]
            bottom_indices = (bottom_indices // S.size(1), bottom_indices % S.size(1))
            nabla_H = t.zeros_like(S)
            nabla_H[bottom_indices] = 1
            return nabla_H

        def delta_residual_hypergraph(S, padd):
            values, indices = t.sort(S.view(-1))
            top_indices = indices[-int(padd * S.numel()):]
            top_indices = (top_indices // S.size(1), top_indices % S.size(1))
            delta_H = t.zeros_like(S)
            delta_H[top_indices] = 1
            return delta_H

        def create_H_hat(original_H, delta_H, nabla_H):
            H_hat = t.clamp(original_H + delta_H - nabla_H, 0, float('inf'))  # 0以下の値を0に、1以上の値を1にクリップ
            return H_hat

        padd = 0.1  # paddの設定（例として0.2）

        # ∆Hと∇Hの計算
        delta_H = delta_residual_hypergraph(S, padd)
        nabla_H = nabla_residual_hypergraph(S, padd)
        H_hat = create_H_hat(H, delta_H, nabla_H)
        Learned_H, _ = self.Laplcian_matrix(H_hat)

        return Learned_H

    def Laplcian_matrix(self, H_hat):
        # ラプラシアン行列の計算関数があると仮定します
        # 実際のラプラシアン行列計算コードに置き換えてください
        # 元のコードの2番目の返り値はこの関数では使用されていません
        # したがって、それに合わせて調整する必要があります
        # この関数がない場合は、要件に基づいて実装する必要があります
        # 例示のため、単にH_hatを返すだけのプレースホルダーとしています
        return H_hat, None

# ランダムなデータ生成
H = t.rand((5, 5))
S = t.rand((5, 5))

# YourClassNameのインスタンスを作成
your_instance = YourClassName()

# LearnedHyperGraphメソッドを呼び出し
result = your_instance.LearnedHyperGraph(H, S)

# 結果を表示
print(result)


tensor([[0.2159, 0.5742, 0.0042, 0.5853, 0.0000],
        [0.2530, 0.2083, 0.5865, 1.1397, 0.8767],
        [0.2459, 0.1843, 0.3081, 1.2387, 0.2236],
        [0.6141, 0.6159, 0.0499, 0.0774, 0.0000],
        [0.8702, 0.1417, 0.7778, 0.5947, 0.8906]])


/tmp/ipykernel_4008/427284596.py:16: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
  top_indices = (top_indices // S.size(1), top_indices % S.size(1))
/tmp/ipykernel_4008/427284596.py:8: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
  bottom_indices = (bottom_indices // S.size(1), bottom_indices % S.size(1))
